apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
    - name: debug-container
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: /config
          name: aggregator-volume
          readOnly: true
  volumes:
    - name: aggregator-volume
      configMap:
          name: aggregator-config
          items:
              - key: application.yaml
                path: application.yaml
