apiVersion: apps/v1
kind: Deployment
metadata:
  name: humidity-microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: humidity-microservice
  template:
    metadata:
      labels:
        app: humidity-microservice
    spec:
      containers:
        - name: humidity-microservice
          image: humidity-microservice:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /app/resources
              name: readings-volume
      volumes:
        - name: readings-volume
          configMap:
            name: readings-config
---
apiVersion: v1
kind: Service
metadata:
  name: humidity-microservice-service
spec:
  type: ClusterIP
  selector:
    app: humidity-microservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
