spring:
    datasource:
        url: "jdbc:h2:mem:testdb"
        driver-class-name: "org.h2.Driver"
        username: "user"  # Default username for H2
        password: "pass"
    h2:
        console:
            enabled: true
            path: /h2-console

server:
    port: 8090